DzulfiqarSiraj/fwg17-vallet-be

index.js

index awal

---

src/controllers/auth.controller.js
src/models/users.model.js
src/routers/auth.router.js
src/routers/index.js

- create endpoint user login
- create users model (findOneByEmail)
- integrate /auth/login to index router

feat: endpoint post /auth/login

---

src/controllers/admin/users.controller.js
src/routers/admin/index.js
src/routers/admin/users.router.js

- crud for admin/users
- integrate admin/users to index router

feat: crud users

---

index.js
src/controllers/admin/transactionTypes.controller.js
src/models/transactionTypes.model.js
src/routers/admin/index.js
src/routers/admin/transactionTypes.router.js
src/routers/index.js

- make end point to get all data transaction types
- make end point to get data by id transaction types
- make end point to create data transaction types
- make end point to update data by id transaction types
- make end point to delete data by id transaction types
- fix: throw error response

feat: add get transaction types

---

src/controllers/admin/wallet.controller.js
src/models/wallet.model.js
src/routers/admin/index.js
src/routers/admin/wallet.router.js

- crud admin/wallet
- integrate admin/wallet to index router
- create wallet model
- create admin/wallet controller

feat: add crud admin/wallet

---

src/controllers/admin/contactList.controller.js
src/models/contactList.model.js
src/routers/admin/contactList.router.js
src/routers/admin/index.js

- crud for admin/contactList
- create contactList models
- create contactList controller for admin/contactList
- integarate admin/contactList to index router

feat: crud contactList

---

src/controllers/admin/testimony.controller.js
src/controllers/admin/transactions.controller.js
src/models/testimony.model.js
src/models/transactionTypes.model.js
src/models/transactions.model.js
src/routers/admin/index.js
src/routers/admin/testimony.router.js
src/routers/admin/transactions.router.js

- make end point to get all data transaction types
- make end point to get data by id transaction types
- make end point to create data transaction types
- make end point to update data by id transaction types
- make end point to delete data by id transaction types

feat: add CRUD for end point testimony

---

src/controllers/admin/testimony.controller.js
src/controllers/admin/transactions.controller.js
src/models/testimony.model.js
src/models/transactionTypes.model.js
src/models/transactions.model.js
src/routers/admin/index.js
src/routers/admin/testimony.router.js
src/routers/admin/transactions.router.js

- make end point to get all data transactions
- make end point to get data by id transactions
- make end point to create data transactions
- make end point to update data by id transactions
- make end point to delete data by id transactions
- fix: sql on testimony for select all data

feat: add all end point for transactions

---

src/controllers/admin/transfers.controller.js
src/models/transfer.model.js
src/routers/admin/index.js
src/routers/admin/transfers.router.js

- crud admin/transfer
- create transfer model
- create transfer controller
- integrate admin/transfer to index router

feat: crud admin/transfer

---

src/controllers/admin/paymentMethods.controller.js
src/models/paymentMethods.model.js
src/routers/admin/index.js
src/routers/admin/paymentMethods.router.js

- crud admin/payment-method
- create payment-method model
- create payment-method controller
- integrate admin/payment-method to index router

feat: crud admin/payment-method

---

src/controllers/auth.controller.js
src/middleware/auth.middleware.js
src/middleware/roleCheck.middleware.js
src/models/users.model.js
src/routers/index.js

- create aunthentication flow
- use token as authorization key
- token payload = id & roles
- role 'admin' only for crud at /admin endpoint
- update on users model findOneByEmail

feat: authentication with role and token

---

src/controllers/admin/users.controller.js

fix where update user password doesn't  hashed

fix: update hash pasword user

---

src/controllers/auth.controller.js
src/controllers/customers/contactList.controller.js
src/models/contactList.model.js
src/models/users.model.js
src/routers/customers/contactList.router.js
src/routers/customers/index.js
src/routers/index.js

- add end point contact list where customer login
- fix: sql auth

feat: add end point contact list by id user

---

src/controllers/auth.controller.js
src/controllers/customers/contactList.controller.js
src/controllers/customers/historyTransactions.controller.js
src/models/contactList.model.js
src/models/historyTransactions.model.js
src/models/users.model.js
src/routers/customers/contactList.router.js
src/routers/customers/historyTransactions.router.js
src/routers/customers/index.js
src/routers/index.js

- make end point to get data history-list by user customer login

feat: history-list by customer login

---

src/controllers/customers/profiles.controller.js
src/models/users.model.js
src/routers/customers/index.js
src/routers/customers/profiles.router.js

- read table users
- get profile data at /customer/profile

feat: get user data for profile

---

src/controllers/customers/transfer.controller.js

fix where update wallet wont happen because of wrong naming of transfer function

fix: wrong usage of wallet model

---

src/controllers/admin/users.controller.js
src/controllers/auth.controller.js
src/routers/auth.router.js

- create auth pin for transfer
- hash cerate and update pin
- integrate /auth/transfer to index router

feat: authentication with pin

---

src/models/historyTransactions.model.js

- fix: sql history transactions

fix: sql history transactions

---

src/controllers/auth.controller.js
src/controllers/customers/changePassword.controller.js
src/routers/auth.router.js
src/routers/customers/changePassword.router.js

- add verifyPassword controller at auth/controller
- delete getPassword at customer/changePassword
- add endpoint verify-password at auth.router
- add customers/changePassword router

feat: profile/change-password

---

src/controllers/auth.controller.js
src/models/wallet.model.js

add another model to auth/register with the purpose of creating wallet when new user register

feat: make wallet for new customer

---

src/controllers/customers/contactList.controller.js
src/models/historyTransactions.model.js
src/models/users.model.js

- create model search users by phone number
- integrate to /customr/contact-list endpoint

update: search by phone number

---

src/controllers/customers/historyTransactions.controller.js
src/models/historyTransactions.model.js

- add feature search in list history transaction
- add feature pagination
- add feature limit data results

fiix: search and limit history transactions

---

mail.helper.js
package-lock.json
package.json
src/controllers/auth.controller.js

- add nodemailer
- add package node mailer
- add package googleapis

feat: nodemailer

---

mail.helper.js

- simpan secret key nodemailer di env

add env nodemailer
